# all available options: https://goreleaser.com/customization/
project_name: summon

before:
  hooks:
  - go mod download

builds:
- binary: summon
  env:
  - CGO_ENABLED=0
  goos:
  - darwin  # MacOS
  - windows
  - linux
  goarch:
  - amd64
  ldflags: []
  main: ./cmd/main.go

archives:
  - id: summon-release-archive
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*  # only package the binary - not defaults: readme, license, changelog

checksum:
  name_template: 'SHA256SUMS.txt'

brews:
  - description: CLI that provides on-demand secrets access for common DevOps tools.
    homepage: https://github.com/ycornamusaz/summon
    url_template: https://github.com/ycornamusaz/summon/releases/download/v{{.Version}}/summon-darwin-amd64.tar.gz
    install: |
      bin.install "summon"
    test: |
      system "#{bin}/summon", "-v"

    github:
      owner: cyberark
      name: homebrew-tools
    skip_upload: true

nfpms:
  - name_template: "{{.ProjectName}}"
    vendor: CyberArk
    homepage: https://github.com/ycornamusaz/summon
    maintainer: Dustin Collins <dustin.collins@cyberark.com>

    description: CLI that provides on-demand secrets access for common DevOps tools.
    recommends:
      - summon-conjur
    license: MIT
    formats:
    - deb
    - rpm
    bindir: /usr/local/bin

release:
  disable: true
  prerelease: auto
